trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  BuildConfiguration: 'Release'

steps:
  - checkout: self
    fetchDepth: 0
  - task: UseDotNet@2
    displayName: 'Install .NET 10 SDK'
    inputs:
      packageType: 'sdk'
      version: '10.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      dotnet tool install --global GitVersion.Tool --version 6.5.1
      export PATH="$PATH:$HOME/.dotnet/tools"
      dotnet-gitversion -output json -config gitversion.yml > gitversion.json
    displayName: 'Install and Run GitVersion 6.5.1'

  - script: |
      NUGET_VERSION=$(jq -r .NuGetPackageVersion gitversion.json)
      FULL_SEMVER=$(jq -r .FullSemVer gitversion.json)
      MAJOR_MINOR_PATCH=$(jq -r .MajorMinorPatch gitversion.json)
      echo "##vso[task.setvariable variable=GitVersion.NuGetVersion]$NUGET_VERSION"
      echo "##vso[task.setvariable variable=GitVersion.FullSemVer]$FULL_SEMVER"
      echo "##vso[task.setvariable variable=GitVersion.MajorMinorPatch]$MAJOR_MINOR_PATCH"
    displayName: 'Export GitVersion variables'

  - script: |
      echo "GitVersion.FullSemVer: ${GitVersion_FullSemVer}"
      echo "GitVersion.NuGetVersion: ${GitVersion_NuGetVersion}"
      echo "GitVersion.MajorMinorPatch: ${GitVersion_MajorMinorPatch}"
    displayName: 'Print GitVersion and NuGetVersion'

  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet tool'

  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet packages'
    inputs:
      command: 'restore'
      projects: '**/*.sln'

  - task: DotNetCoreCLI@2
    displayName: 'Build solution'
    inputs:
      configuration: $(BuildConfiguration)
      arguments: '--no-restore'

  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: 'test'
      projects: '**/*.sln'
      arguments: '--configuration $(BuildConfiguration) --no-build'

  - task: DotNetCoreCLI@2
    displayName: 'Pack NuGet'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    inputs:
      command: 'pack'
      configuration: $(BuildConfiguration)
      arguments: '--no-build /p:PackageVersion=$(GitVersion.NuGetVersion)'
      packagesToPack: 'Prediktor.UA.Client/Prediktor.UA.Client.csproj'
      outputDir: '$(Build.ArtifactStagingDirectory)'

  - task: DotNetCoreCLI@2
    displayName: 'Push NuGet'
    inputs:
      command: 'custom'
      custom: 'nuget'
      arguments: >
        push $(Build.ArtifactStagingDirectory)/**/*.nupkg
        --api-key $(NUGET_PUBLISH_KEY)
        --source https://api.nuget.org/v3/index.json
        --skip-duplicate

  - script: |
      git config --global user.email "rd_relmgr@prediktor.no"
      git config --global user.name "Build Pipeline"
      git tag $(GitVersion.MajorMinorPatch)
      git push origin $(GitVersion.MajorMinorPatch)
    displayName: 'Tag repo with latest version and push'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))


