trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  BuildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 10 SDK'
    inputs:
      packageType: 'sdk'
      version: '10.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
     dotnet tool install --global GitVersion.Tool --version 6.5.1
     export PATH="$PATH:$HOME/.dotnet/tools"
     GitVersion -output buildserver -config gitversion.yml
    displayName: 'Install and Run GitVersion 6.5.1'

  - script: |
      echo "GitVersion.FullSemVer: $(GitVersion.FullSemVer)"
      echo "GitVersion.NuGetVersion: $(GitVersion.NuGetVersion)"
      echo "GitVersion.MajorMinorPatch: $(GitVersion.MajorMinorPatch)"
    displayName: 'Print GitVersion and NuGetVersion'

  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet tool'

  - task: NuGetCommand@2
    displayName: 'Restore NuGet packages'
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'config'
      externalFeedCredentials: 'Pred_nuget_03032023'

  - task: DotNetCoreCLI@2
    displayName: 'Build solution'
    inputs:
      configuration: $(BuildConfiguration)
      arguments: '--no-restore'

  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: 'test'
      projects: '**/*.sln'
      arguments: '--configuration $(BuildConfiguration) --no-build'

  - task: DotNetCoreCLI@2
    displayName: 'Pack NuGet'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    inputs:
      command: 'pack'
      configuration: $(BuildConfiguration)
      arguments: '--no-build /p:PackageVersion=$(GitVersion.NuGetVersion)'
      packagesToPack: '**/*.csproj'
      outputDir: '$(Build.ArtifactStagingDirectory)'

  - task: DotNetCoreCLI@2
    displayName: 'Push NuGet'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'Pred_nuget_03032023'
      arguments: '--skip-duplicate'

  - script: |
      git config --global user.email "rd_relmgr@prediktor.no"
      git config --global user.name "Build Pipeline"
      git tag $(GitVersion.MajorMinorPatch)
      git push origin $(GitVersion.MajorMinorPatch)
    displayName: 'Tag repo with latest version and push'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))


